version: '3'
services:
  enedis-back:
    build: .
    volumes: 
      - ..:/usr/app
    command: yarn start
    ports:
      - 3001:3001
  enedis-db:
    image: postgres:alpine
    environment:
    - DB_USER=admin
    - DB_PASS=password
    - DB_NAME=test